### ISSUE TITLE
Convert and generate data after training

### ISSUE THREAD

**Issue by dvthuytran** [yasserben/DATUM#1]
Hi @yasserben,

After fine-tuning DreamBooth, I would like to generate data but it gives an error:

ModuleNotFoundError: No module named 'my_utils'

Please update this module. Thank you.

**Comment by yasserben** [comment]
Hi @tdvinhthuy 

Thanks for pointing out this problem.
I added `my_utils` to the `dreambooth` folder and it should be copy/pasted with the 3 python scripts as well. (I added it in the README as well)
