### ISSUE TITLE
Small feedback

### ISSUE THREAD

**Issue by wnbilly** [yasserben/DATUM#2]
Hi, while using your super project, I noted some improvement points :

- In the setup datasets part, gt_trainvaltest.zip should be gtFine_trainvaltest.zip
- train_dreambooth.py saves checkpoints and others in DATUM/diffusers/examples/NAME_OF_EXPERIMENT and convert_dreambooth.py looks for files in DATUM/diffusers/examples/dreambooth/logs
- Import error (DAFormer.experiments instead of experiments in run_experiments.py)
- The generated dataset is saved in DATUM/diffusers/examples/dreambooth/logs/images/NAME_OF_EXPERIMENT/NAME_OF_EXPERIMENT_eXXX whereas run_experiments.py looks for files in the data folder (solved by moving the generated dataset to the data folder)

**Comment by yasserben** [comment]
Thank you for your comments, I corrected all the mistakes you pointed out
