### ISSUE TITLE
How to obtain training images of the target domain?

### ISSUE THREAD

**Issue by ddghjikle** [yasserben/DATUM#3]
Hi, thanks for releasing codes. Could you please specify how to randomly obtain training images of the target domain? It seems that released codes do not contain the function of randomly choosing.

**Comment by yasserben** [comment]
Hi @ddghjikle , sorry for the late reply !
Indeed, the code doesn't contain a script which randomly chooses the single target domain.
As it was specified in the README, you can choose any image you want from the training set of Cityscapes and use it to personalize your text-to-image diffusion model.
In our paper we chose the following three random images and we averaged the results over them : 
stuttgart_000016_000019_leftImg8bit.png
cologne_000115_000019_leftImg8bit.png
cologne_000006_000019_leftImg8bit.png
