### ISSUE TITLE
Can you provide the checkpoint for Personalization stage?

### ISSUE THREAD

**Issue by wanderHZ** [yasserben/DATUM#4]
It's a great work! And, I would like to replicate the results represented in this paper. Can you provide the checkpoint for Personalization stage?

**Comment by yasserben** [comment]
Hi, thanks !
Here's one pretrained StableDiffusion with the image used for personalization : https://drive.google.com/file/d/1TMFoYO0mOE57TeCTunPWWZ4evJccIE6N/view?usp=sharing
This is the one which has the median value over the three random seeds, and was used for ablation studies as well.
