### ISSUE TITLE
Image generation size

### ISSUE THREAD

**Issue by Jumponthemoon** [yasserben/DATUM#7]
Hi,

Appreciate your brilliant work!

Just a quick question. If the training size and generating size can be done without crop works?

**Comment by Jumponthemoon** [comment]
I mean how to generate images other than 512x512? I saw  samples in Figure 3 in the papers are not square.

**Comment by yasserben** [comment]
Hi ! Sorry for the late reply.In DATUM, we created 512x512 images using the default settings of the fine-tuned Stable Diffusion 1.5, which is set to generate images of that size.For clarity in the manuscript, the images in Figure 3 were resized.Hope this helps clarify things!

**Comment by Jumponthemoon** [comment]
Understood. Thanks for your clarification!
